# # This workflow will do a clean install of node dependencies, 
# # build the source code and run tests across different versions of node
# # For more information see: 
# # https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# 
# name: Let's go CI
# 
# on:
#   push:
#     branches: [ main ]
# 
# jobs:
#   build:
#     runs-on: ubuntu-22.04
# 
#     steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js 18
#       uses: actions/setup-node@v3
#       with:
#         node-version: 18
#     # - name: Install Composer Dependencies
#       # working-directory: ./nextjs-app
#       # run: yarn install
#       # run: yarn build --if-present
